version: 1

builds:
  - src: ./server
    use: node
    cmd: npm install && npm start

routes:
  - src: /health
    dest: /health
  - src: /api/.*
    dest: /api/$1
  - src: /socket.io/.*
    dest: /socket.io/$1
  - src: /.*
    dest: /

env:
  NODE_ENV: production
  PORT: 5000
